- name: Demo on variables    #play level variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a variable
      debug:
        msg: "URL = {{URL}}"
    - name: Print task variable
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.yahoo.com

- name: Demo on Inv variables    #Inventory level variables
  hosts: all
  tasks:
    - name: Print a variable
      debug:
        msg: "URL = {{URL}}"

