- name: Demo on variables    #play level variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a variable
      debug:
        msg: "URL = {{URL}}"
    - name: Print task variable
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.yahoo.com

- name: Demo on Inv variables    #Inventory level variables
  hosts: all
  tasks:
    - name: Print a variable
      debug:
        msg: "URL = {{URL}}"

- name: Demo on File variables    #variables for file
  hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Print a variable
      debug:
        msg: "URL = {{URL}}"

- name: Demo on Facts    #demo on facts
  hosts: all
  tasks:
    - name: Print a variable
      debug:
        msg: "Hostname = {{ansible_fqdn}}"

- name: Demo on register variaable
  hosts: all
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: out

    - name: set a variable
      ansible.builtin.set_fact:
        UPTIME: "{{out.stdout}}"

    - name: Print output
      debug:
        msg: "{{UPTIME}}"

- name: Demo on roles
  hosts: all
  roles:
    - name: demo




