- name: Demo on variables    #play level variables
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: Print a variable
      debug:
        msg: "URL = {{URL}}"
    - name: Print task variable
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: yahoo.com

