- name: Demo on when conditions
  hosts: localhost
  vars:
    URL: yahoo.com
    a: 10
  tasks:
    - name: Condition on strings
      when: URL == "yahoo.org"
      debug:
        msg: Hello

    - name: Condition on strings
      when: URL != "yahoo.org"
      debug:
        msg: Hello

    - name: Condition on numbers
      when: a != 10
      debug:
        msg: Hello

    - name: Run if variable B is defined
      when: B is not defined
      debug:
        msg: Hello

    - name: Run if variable B is defined and a is greater than 10
      when: B is defined and a >= 10
      debug:
        msg: Hello
