- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

#Dynamically loads and executes a specified role as a task.
- name: Download and Extract Frontend content
  include_role:
    name: common
    tasks_from: Download

- name: Copy the extracted content
  copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy roboshop configure
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: restart Nginx Service
  systemd:
    name: nginx
    state: restarted
    enabled: yes


