- name: Check node exporter does exist  #if directory doesn't exists it is going to be true
  stat:
    path: /opt/node_exporter
  register: out

- name: Install Node Exporter
  when: not out.stat.exists   #if it is true running these next steps
  block:
    - name: Download Prometheus Archive
      unarchive:
        src: "{{NODE_EXPORTER_URL}}"
        dest: /tmp
        remote_src: yes

    - name: Copy Node Exporter to /opt
      copy:
        src: /tmp/{{ NODE_EXPORTER_URL | split('/') | last | regex_replace('.tar.gaz', '') }}
        dest: /opt/node_exporter
        remote_src: yes

