- name: Install NodeJS
  yum:    #yum mmodule supports multiple pacakges and we list
    name: ["nodejs", "make", "gcc-c++"]
    state: present

- name: Add RoboShop Application User
  ansible.builtin.user:
    name: roboshop

- name: Download from Github
  include_tasks:
    file: download.yml  #will decide wher to download the file

- name: Copy the extracted content
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop   #root directory has to be set with permissions of roboshop user
    group: roboshop

#npm install should be running as roboshopuser, Now i'm root user and become a roboshop user and seup these
- name: Install {{COMPONENT}} Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop   #Now i'm root user and become a roboshop user and setup these using become_user

- name: Update sysstemD Configuration
  copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restart {{COMPONENT}} Service
  systemd:
    name: {{COMPONENT}}   #hardcoded value we are parametrizing with component
    state: restarted
    enabled: yes
    daemon_reload: yes
