- name: Add RoboShop Application User
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: Download from Github
  include_tasks:
    file: download-from-github.yml

#additional stepup for future

#these download will decide you, where to go
#download.yml should load another task file

- name: Delete Old App Code
  file:
    path: /home/roboshop/{{COMPONENT}}/
    state: absent

- name: Copy the extracted content
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop   #root directory has to be set with permissions of roboshop user
    group: roboshop