- name: Update SystemD Configuration
  copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restart {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: started
    enabled: yes
    daemon_reload: yes
