- name: Update SystemD Configuration
  copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
  notify: Restart Service - Handler

- name: Restart {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes

